language: python
python:
  - "3.6"

sudo: false

script:
  - python --version

before_deploy:
  - python course2jekyll.py 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _staticsite
  on:
    branch: master
